// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { useGSAP } from "@gsap/react";
// import gsap from "gsap";

// export function Planet(props) {
//   const shapeContainer = useRef(null);
//   const shperesContainer = useRef(null);
//   const ringContainer = useRef(null);
//   const { nodes, materials } = useGLTF("/models/Planet.glb");

//   useGSAP(() => {
//     const tl = gsap.timeline();
//     tl.from(shapeContainer.current.position, {
//       y: 5,
//       duration: 3,
//       ease: "circ.out",
//     });
//     tl.from(
//       shperesContainer.current.rotation,
//       {
//         x: 0,
//         y: Math.PI,
//         z: -Math.PI,
//         duration: 10,
//         ease: "power1.inOut",
//       },
//       "-=25%"
//     );
//     tl.from(
//       ringContainer.current.rotation,
//       {
//         x: 0.8,
//         y: 0,
//         z: 0,
//         duration: 10,
//         ease: "power1.inOut",
//       },
//       "<"
//     );
//   }, []);

//   return (
//     <group ref={shapeContainer} {...props} dispose={null}>
//       <group ref={shperesContainer}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Sphere.geometry}
//           material={materials["Material.002"]}
//           rotation={[0, 0, 0.741]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Sphere2.geometry}
//           material={materials["Material.001"]}
//           position={[0.647, 1.03, -0.724]}
//           rotation={[0, 0, 0.741]}
//           scale={0.223}
//         />
//       </group>
//       <mesh
//         ref={ringContainer}
//         castShadow
//         receiveShadow
//         geometry={nodes.Ring.geometry}
//         material={materials["Material.001"]}
//         rotation={[-0.124, 0.123, -0.778]}
//         scale={2}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/Planet.glb");
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
// Import komponen material Three.js
import { MeshStandardMaterial, Color } from "three";

export function Planet(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  const planetMaterial = new MeshStandardMaterial({
    color: new Color("#0B1530"),
  });
  const ringMaterial = new MeshStandardMaterial({
    color: new Color("#D3D6DC"),
  });
  const satelliteMaterial = new MeshStandardMaterial({
    color: new Color("#7C8FB0"),
  });

  useGSAP(() => {
    const tl = gsap.timeline();

    // Animasi muncul dari bawah
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });

    // Animasi rotasi shperesContainer (planet utama & satelit)
    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%"
    );

    // Animasi rotasi ringContainer
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );

    // Animasi Loop (Tambahan): Rotasi shperesContainer terus menerus setelah intro
    gsap.to(shperesContainer.current.rotation, {
      y: Math.PI * 2, // Rotasi 360 derajat di sumbu Y
      duration: 30, // Durasi rotasi (lebih lambat)
      ease: "none", // Rotasi konstan
      repeat: -1, // Ulangi tak terbatas
      delay: tl.duration(), // Mulai setelah timeline intro selesai
    });

    // Animasi Loop (Tambahan): Rotasi ringContainer terus menerus setelah intro
    gsap.to(ringContainer.current.rotation, {
      y: Math.PI * 2, // Rotasi 360 derajat di sumbu Y
      duration: 20, // Durasi rotasi
      ease: "none", // Rotasi konstan
      repeat: -1, // Ulangi tak terbatas
      delay: tl.duration(), // Mulai setelah timeline intro selesai
    });
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        {/* Planet Utama (Sphere) */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={planetMaterial} // <--- Menggunakan material kustom untuk Planet
          rotation={[0, 0, 0.741]}
        />
        {/* Satelit (Sphere2) */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={satelliteMaterial} // <--- Menggunakan material kustom untuk Satelit
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      {/* Cincin (Ring) */}
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={ringMaterial} // <--- Menggunakan material kustom untuk Cincin
        rotation={[-0.124, 0.123, -0.778]}
        scale={1.6}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
